# Generated by Django 5.2.8 on 2025-12-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Image for dropdown preview', null=True, upload_to='hotel_thumbnails/'),
        ),
    ]
